name: Bundle

on:
  push:
  workflow_call:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'mvn'

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - run: yarn install

      - run: yarn bundle

      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: apps/executable-app-api/target/executable-app-api-0.0.1-SNAPSHOT.jar

      - uses: actions/upload-artifact@v3
        with:
          name: win
          path: apps/executable-app-api/target/executable-app-api.exe
